spring:
  application:
    name: itoken-service-mb
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
  shardingsphere:
    datasource:
      names: master,slave,sy_db0,sy_db1
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/stytest?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
        username: root
        password: root@7321
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/stytest1?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
        username: root
        password: root@7321
      sy_db0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sy_db0?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
        username: root
        password: root@7321
      sy_db1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sy_db1?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
        username: root
        password: root@7321
    masterslave:
      load-balance-algorithm-type: round_robin
      name: dataSource
      master-data-source-name: master
      slave-data-source-names: slave
    props:
      sql:
        show: true
    sharding:
      default-database-strategy:
        standard:
          sharding-column: user_id
          precise-algorithm-class-name: com.cloud.service.mb.sharding.PreciseShardingAlgorithmImpl
      tables:
        t_item:
          actual-data-nodes: sy_db$->{0..1}.t_item$->{0..1}
          table-strategy:
            inline:
              sharding-column: item_id
              algorithm-expression: t_item$->{item_id % 2}
      binding-tables: t_item
  redis:
    database: 0
    host: 127.0.0.1
    port: 6380
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000

mybatis:
  type-aliases-package: com.cloud.service.mb.pojo
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8766

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info
