spring:
  application:
    name: itoken-server
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
  data:
    solr:
      host: http://127.0.0.1:8983/solr

server:
  port: 8767

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info
